rdmo/projects/models/issue.py
from datetime import date, timedelta
from itertools import zip_longest

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from rdmo.tasks.models import Task

from ..managers import IssueManager


class Issue(models.Model):

    objects = IssueManager()

    ISSUE_STATUS_OPEN = 'open'
    ISSUE_STATUS_IN_PROGRESS = 'in_progress'
    ISSUE_STATUS_CLOSED = 'closed'
    ISSUE_STATUS_CHOICES = (
        (ISSUE_STATUS_OPEN, _('open')),
        (ISSUE_STATUS_IN_PROGRESS, _('in progress')),
        (ISSUE_STATUS_CLOSED, _('closed'))
    )

    project = models.ForeignKey(
        'Project', on_delete=models.CASCADE, related_name='issues',
        verbose_name=_('Project'),
        help_text=_('The project for this issue.')
    )
    task = models.ForeignKey(
        Task, on_delete=models.CASCADE, related_name='issues',
        verbose_name=_('Task'),
        help_text=_('The task for this issue.')
    )
    status = models.CharField(
        max_length=12, choices=ISSUE_STATUS_CHOICES, default=ISSUE_STATUS_OPEN,
        verbose_name=_('Status'),
        help_text=_('The status for this issue.')
    )

    class Meta:
        ordering = ('project__title', )
        verbose_name = _('Issue')
        verbose_name_plural = _('Issues')

    def __str__(self):
        return '%s / %s / %s' % (self.project.title, self.task, self.status)

    def get_absolute_url(self):
        return reverse('project', kwargs={'pk': self.project.pk})

    def resolve(self, values):
        for condition in self.task.conditions.all():
            if condition.resolve(values):
                return True

    @property
    def dates(self):
        values = self.project.values.filter(snapshot=None)

        if self.task.start_attribute:
            start_values = values.filter(attribute=self.task.start_attribute)
        else:
            start_values = []

        if self.task.end_attribute:
            end_values = values.filter(attribute=self.task.end_attribute)
        else:
            end_values = []

        days_before = timedelta(self.task.days_before) if self.task.days_before else timedelta()
        days_after = timedelta(self.task.days_after) if self.task.days_after else timedelta()

        dates = []
        for start_value, end_value in zip_longest(start_values, end_values):

            if start_value and start_value.value and isinstance(start_value.value, date):
                start_date = start_value.value
            else:
                start_date = None

            if end_value and end_value.value and isinstance(end_value.value, date):
                end_date = end_value.value
            else:
                end_date = None

            if start_date and end_date:
                dates.append((start_date - days_before, end_date + days_after))
            elif start_date:
                dates.append((start_date - days_before + days_after, ))
            elif end_date:
                dates.append((end_date - days_before + days_after, ))

        return dates


class IssueResource(models.Model):

    issue = models.ForeignKey(
        'Issue', on_delete=models.CASCADE, related_name='resources',
        verbose_name=_('Issue'),
        help_text=_('The issue for this issue resource.')
    )
    integration = models.ForeignKey(
        'Integration', on_delete=models.CASCADE, related_name='resources',
        verbose_name=_('Integration'),
        help_text=_('The integration for this issue resource.')
    )
    url = models.URLField(
        verbose_name=_('URL'),
        help_text=_('The URL of this issue resource.')
    )

    class Meta:
        ordering = ('issue__project__title', 'issue')
        verbose_name = _('Issue resource')
        verbose_name_plural = _('Issue resources')

    def __str__(self):
        return '%s / %s / %s' % (self.issue.project.title, self.issue, self.url)

rdmo/projects/views/integration.py
import logging

from django.http import Http404
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView, DeleteView, UpdateView, View

from rdmo.core.plugins import get_plugin
from rdmo.core.views import ObjectPermissionMixin, RedirectViewMixin

from ..forms import IntegrationForm
from ..models import Integration, Project

logger = logging.getLogger(__name__)


class IntegrationCreateView(ObjectPermissionMixin, RedirectViewMixin, CreateView):
    model = Integration
    form_class = IntegrationForm
    permission_required = 'projects.add_integration_object'

    def dispatch(self, *args, **kwargs):
        self.project = get_object_or_404(Project.objects.all(), pk=self.kwargs['project_id'])
        self.provider_key = self.kwargs['provider_key']
        return super().dispatch(*args, **kwargs)

    def get_permission_object(self):
        return self.project

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project'] = self.project
        kwargs['provider_key'] = self.provider_key
        return kwargs

    def get_context_data(self, **kwargs):
        kwargs['provider'] = get_plugin('PROJECT_ISSUE_PROVIDERS', self.provider_key)
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return self.project.get_absolute_url()


class IntegrationUpdateView(ObjectPermissionMixin, RedirectViewMixin, UpdateView):
    form_class = IntegrationForm
    permission_required = 'projects.change_integration_object'

    def get_queryset(self):
        return Integration.objects.filter(project_id=self.kwargs.get('project_id'))

    def get_permission_object(self):
        return self.get_object().project

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['project'] = self.get_object().project
        return kwargs

    def get_context_data(self, **kwargs):
        kwargs['provider'] = self.get_object().provider
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return self.get_object().project.get_absolute_url()


class IntegrationDeleteView(ObjectPermissionMixin, RedirectViewMixin, DeleteView):
    permission_required = 'projects.delete_integration_object'

    def get_queryset(self):
        return Integration.objects.filter(project_id=self.kwargs.get('project_id'))

    def get_permission_object(self):
        return self.get_object().project

    def get_success_url(self):
        return self.get_object().project.get_absolute_url()


@method_decorator(csrf_exempt, name='dispatch')
class IntegrationWebhookView(View):

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        project_id = kwargs.get('project_id')

        try:
            integration = Integration.objects.filter(project_id=project_id).get(pk=pk)
            return integration.provider.webhook(request, integration)
        except Integration.DoesNotExist:
            raise Http404

rdmo/projects/views/issue.py
import logging

from django.conf import settings
from django.contrib.sites.models import Site
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import TemplateSyntaxError
from django.template.loader import render_to_string
from django.views.generic import DetailView, UpdateView
from rest_framework.reverse import reverse

from rdmo.core.mail import send_mail
from rdmo.core.utils import render_to_format
from rdmo.core.views import ObjectPermissionMixin, RedirectViewMixin
from rdmo.views.utils import ProjectWrapper

from ..forms import IssueMailForm, IssueSendForm
from ..models import Issue
from ..utils import get_value_path

logger = logging.getLogger(__name__)


class IssueDetailView(ObjectPermissionMixin, DetailView):
    permission_required = 'projects.view_issue_object'

    def get_queryset(self):
        return Issue.objects.filter(project_id=self.kwargs.get('project_id'))

    def get_permission_object(self):
        return self.get_object().project

    def get_context_data(self, **kwargs):
        project = self.get_object().project
        conditions = self.get_object().task.conditions.all()

        sources = []
        for condition in conditions:
            sources.append({
                'source': condition.source,
                'questions': condition.source.questions.filter(questionset__section__catalog=project.catalog),
                'values': condition.source.values.filter(project=project, snapshot=None)
            })

        kwargs['project'] = project
        kwargs['sources'] = sources
        return super().get_context_data(**kwargs)


class IssueUpdateView(ObjectPermissionMixin, RedirectViewMixin, UpdateView):
    fields = ('status', )
    permission_required = 'projects.change_issue_object'

    def get_queryset(self):
        return Issue.objects.filter(project_id=self.kwargs.get('project_id'))

    def get_permission_object(self):
        return self.get_object().project


class IssueSendView(ObjectPermissionMixin, RedirectViewMixin, DetailView):
    permission_required = 'projects.change_issue_object'
    template_name = 'projects/issue_send.html'

    def dispatch(self, *args, **kwargs):
        if not settings.PROJECT_SEND_ISSUE:
            raise Http404

        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return Issue.objects.filter(project_id=self.kwargs.get('project_id'))

    def get_permission_object(self):
        return self.get_object().project

    def get_success_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        else:
            return self.get_object().project.get_absolute_url()

    def get_context_data(self, **kwargs):
        self.object = self.get_object()

        issue = self.object
        project = self.get_object().project
        project_url = self.request.build_absolute_uri(project.get_absolute_url())
        site = Site.objects.get_current()
        site_url = self.request.build_absolute_uri(reverse('home'))

        if 'form' not in kwargs:
            template_context = {
                'issue': issue,
                'project': project,
                'project_url': project_url,
                'site': site,
                'site_url': site_url,
                'user': self.request.user
            }
            subject = render_to_string('projects/issue_send_subject.txt', template_context, request=self.request)
            message = render_to_string('projects/issue_send_message.txt', template_context, request=self.request)

            kwargs['form'] = IssueSendForm(initial={
                'subject': subject,
                'message': message
            }, project=project)

        if 'mail_form' not in kwargs:
            kwargs['mail_form'] = IssueMailForm()

        context = super().get_context_data(**kwargs)
        context['views'] = project.views.all()
        context['integrations'] = project.integrations.all()
        return context

    def post(self, request, *args, **kwargs):
        issue = self.get_object()
        project = issue.project

        form = IssueSendForm(request.POST, project=project)
        mail_form = IssueMailForm(request.POST)

        if form.is_valid():
            subject = form.cleaned_data.get('subject')
            message = form.cleaned_data.get('message')

            snapshot = project.snapshots.filter(pk=form.cleaned_data.get('snapshot')).first()
            attachments_format = form.cleaned_data.get('attachments_format')

            attachments = []
            if form.cleaned_data.get('attachments_answers'):
                title = '{}.{}'.format(project.title, attachments_format)
                response = self.render_project_answers(project, snapshot, attachments_format)
                attachments.append((title, response.content, response['content-type']))

            for view in form.cleaned_data.get('attachments_views'):
                title = '{}.{}'.format(project.title, attachments_format)
                response = self.render_project_views(project, snapshot, view, attachments_format)
                attachments.append((title, response.content, response['content-type']))

            for value in form.cleaned_data.get('attachments_files'):
                attachments.append((value.file_name, value.file.read(), value.file_type))

            integration_id = request.POST.get('integration')
            if integration_id:
                # send via integration
                try:
                    integration = project.integrations.get(pk=integration_id)
                    return integration.provider.send_issue(request, issue, integration, subject, message, attachments)
                except (ObjectDoesNotExist, AttributeError):
                    pass
            else:
                if mail_form.is_valid():
                    to_emails = mail_form.cleaned_data.get('recipients', []) + mail_form.cleaned_data.get('recipients_input', [])
                    cc_emails = [request.user.email]
                    reply_to = [request.user.email]

                    # send the email
                    send_mail(subject, message, to=to_emails, cc=cc_emails, reply_to=reply_to, attachments=attachments)

                    # update issue status
                    issue.status = Issue.ISSUE_STATUS_IN_PROGRESS
                    issue.save()

                    return HttpResponseRedirect(self.get_success_url())

        return self.render_to_response(self.get_context_data(form=form, mail_form=mail_form))

    def render_project_answers(self, project, snapshot, attachments_format):
        return render_to_format(self.request, attachments_format, project.title, 'projects/project_answers_export.html', {
            'project': ProjectWrapper(project, snapshot),
            'format': attachments_format,
            'title': project.title,
            'resource_path': get_value_path(project, snapshot)
        })

    def render_project_views(self, project, snapshot, view, attachments_format):
        try:
            rendered_view = view.render(project, snapshot)
        except TemplateSyntaxError:
            return HttpResponse()

        return render_to_format(self.request, attachments_format, project.title, 'projects/project_view_export.html', {
            'format': attachments_format,
            'title': project.title,
            'view': view,
            'rendered_view': rendered_view,
            'resource_path': get_value_path(project, snapshot)
        })

rdmo/projects/views/snapshot.py
import logging

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, DetailView, UpdateView

from rdmo.core.views import ObjectPermissionMixin, RedirectViewMixin

from ..forms import SnapshotCreateForm
from ..models import Project, Snapshot

logger = logging.getLogger(__name__)


class SnapshotCreateView(ObjectPermissionMixin, RedirectViewMixin, CreateView):
    model = Snapshot
    form_class = SnapshotCreateForm
    permission_required = 'projects.add_snapshot_object'

    def dispatch(self, *args, **kwargs):
        self.project = get_object_or_404(Project.objects.all(), pk=self.kwargs['project_id'])
        return super(SnapshotCreateView, self).dispatch(*args, **kwargs)

    def get_permission_object(self):
        return self.project

    def get_form_kwargs(self):
        kwargs = super(SnapshotCreateView, self).get_form_kwargs()
        kwargs['project'] = self.project
        return kwargs


class SnapshotUpdateView(ObjectPermissionMixin, RedirectViewMixin, UpdateView):
    model = Snapshot
    queryset = Snapshot.objects.all()
    fields = ['title', 'description']
    permission_required = 'projects.change_snapshot_object'

    def get_queryset(self):
        return Snapshot.objects.filter(project_id=self.kwargs['project_id'])

    def get_permission_object(self):
        return self.get_object().project


class SnapshotRollbackView(ObjectPermissionMixin, RedirectViewMixin, DetailView):
    model = Snapshot
    queryset = Snapshot.objects.all()
    permission_required = 'projects.rollback_snapshot_object'
    template_name = 'projects/snapshot_rollback.html'

    def get_queryset(self):
        return Snapshot.objects.filter(project_id=self.kwargs['project_id'])

    def get_permission_object(self):
        return self.get_object().project

    def post(self, request, *args, **kwargs):
        snapshot = self.get_object()

        if 'cancel' not in request.POST:
            snapshot.rollback()

        return HttpResponseRedirect(reverse('project', args=[snapshot.project.id]))

rdmo/projects/templates/projects/integration_confirm_delete.html
{% extends 'core/page.html' %}
{% load i18n %}
{% load core_tags %}

{% block page %}

    <h1>{% trans "Delete integration" %}</h1>

    <p>
        {% blocktrans with label=object.provider.label %}You are about to permanently delete the <strong>{{ label }}</strong>.{% endblocktrans %}
    </p>

    <p class="text-danger">
        {% trans 'This action cannot be undone!' %}
    </p>

    {% bootstrap_delete_form submit=_('Delete integration') %}

{% endblock %}

rdmo/projects/templates/projects/integration_form.html
{% extends 'core/page.html' %}
{% load i18n %}
{% load core_tags %}

{% block page %}

{% if object %}

    <h1>{% trans 'Update integration' %}</h1>

    <p class="help-block">{{ provider.description }}</p>

    {% bootstrap_form submit=_('Update integration') %}

{% else %}

    <h1>{% trans 'Add integration to project' %}</h1>

    <p class="help-block">{{ provider.description }}</p>

    {% bootstrap_form submit=_('Add integration') %}

{% endif %}

{% endblock %}

rdmo/projects/templates/projects/invite_confirm_delete.html
{% extends 'core/page.html' %}
{% load i18n %}
{% load core_tags %}
{% load accounts_tags %}

{% block page %}

    <h1>{% trans 'Delete invite' %}</h1>

    <p>
        {% if object.user %}
        {% full_name object.user as user %}
        {% blocktrans with object.project.title as title trimmed %}
        You are about to remove the invite of <strong>{{ user }}</strong> from the project <strong>{{ title }}</strong>.
        {% endblocktrans %}
        {% else %}
        {% with object.email as user %}
        {% blocktrans with object.project.title as title trimmed %}
        You are about to remove the invite of <strong>{{ user }}</strong> from the project <strong>{{ title }}</strong>.
        {% endblocktrans %}
        {% endwith %}
        {% endif %}
    </p>

    {% bootstrap_delete_form submit=_('Delete invite') %}

{% endblock %}

rdmo/projects/templates/projects/issue_detail.html
{% extends 'core/page.html' %}
{% load i18n %}
{% load core_tags %}

{% block head %}
<script>
    $(document).ready(function() {
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>
{% endblock %}

{% block page %}

<h1>{% trans 'Task' %}</h1>

<h2>{{ issue.task.title }}</h2>

<p>
    {{ issue.task.text|markdown }}
</p>

{% if issue.dates %}

<h3>{% trans 'Dates' %}</h3>

{% for dates in issue.dates %}
    {% if dates|length > 1 %}
    <p>{{ dates.0 | date:"DATE_FORMAT" }}<br /> - {{ dates.1 | date:"DATE_FORMAT" }}</p>
    {% else %}
    <p>{{ dates.0 | date:"DATE_FORMAT" }}</p>
    {% endif %}
{% endfor %}

{% endif %}

<h3>{% trans 'Questions' %}</h3>

<p>
    {% trans 'This task is active, because of the answers to the following questions:' %}
</p>

<ul>
{% for source in sources %}
    <li>
        {% for question in source.questions %}
        <p><strong>{{ question.text }}</strong></p>
        {% endfor %}

        {% for value in source.values %}
        <p>{{ value.value_and_unit }}</p>
        {% endfor %}
    </li>
{% endfor %}
</ul>

{% if issue.resources.all %}

<h3>{% trans 'External resources for this task' %}</h3>

<ul>
{% for resource in issue.resources.all %}
    <li>
        <a href="{{ resource.url }}">{{ resource.url }}</a>
    </li>
{% endfor %}
</ul>

{% endif %}

{% endblock %}

{% block sidebar %}

    <h2>{% trans 'Status' %}</h2>

    <p>
        {{ issue.get_status_display }}
    </p>

    <h2>{% trans 'Options' %}</h2>

    <ul class="list-unstyled">
        <li>
            <a href="{% url 'issue_update' project.pk issue.pk %}?next={{ request.path }}">
                {% trans 'Update task status' %}
            </a>
        </li>
        {% if settings.PROJECT_SEND_ISSUE %}
        <li>
            <a href="{% url 'issue_send' project.pk issue.pk %}?next={{ request.path }}">
                {% trans 'Send task' %}
            </a>
        </li>
        {% endif %}
    </ul>

{% endblock %}

rdmo/projects/templates/projects/project_detail_issues_help.html
{% load i18n %}

    <p class="text-muted">
        {% blocktrans trimmed %}
        Tasks are generated automatically from the answers given in the project. On the page of each task you can see which of your answers lead to the activation of the task.
        {% endblocktrans %}
    </p>

rdmo/projects/templates/projects/project_detail_sidebar.html
{% load i18n %}
{% load rules %}
{% load core_tags %}

{% has_perm 'projects.change_project_object' request.user project as can_change_project %}
{% has_perm 'projects.delete_project_object' request.user project as can_delete_project %}
{% has_perm 'projects.leave_project_object' request.user project as can_leave_project %}

{% has_perm 'projects.change_value_object' request.user project as can_change_value %}

<h2>{% trans 'Options' %}</h2>

<ul class="list-unstyled">
    <li id="project-questions">
        <strong>
            {% if can_change_value %}
            <a href="{% url 'project_questions' project.pk %}">{% trans 'Answer questions' %}</a>
            {% else %}
            <a href="{% url 'project_questions' project.pk %}">{% trans 'View questions' %}</a>
            {% endif %}
        </strong>
    </li>
</ul>

<ul class="list-unstyled">
    <li>
        <strong>
            <a href="{% url 'project_answers' project.pk %}">{% trans 'View answers' %}</a>
        </strong>
    </li>
</ul>

{% if can_leave_project and membership and not membership.is_last_owner %}
<ul class="list-unstyled">
    <li>
        <a href="{% url 'project_leave' project.pk %}">{% trans 'Leave project' %}</a>
    </li>
</ul>
{% endif %}

{% if can_change_project or can_delete_project %}
<ul class="list-unstyled">
    {% if can_change_project %}
    <li>
        <a href="{% url 'project_update_information' project.pk %}">{% trans 'Update project information' %}</a>
    </li>
    <li>
        <a href="{% url 'project_update_catalog' project.pk %}">{% trans 'Update project catalog' %}</a>
    </li>
    {% if settings.NESTED_PROJECTS %}
    <li>
        <a href="{% url 'project_update_parent' project.pk %}">{% trans 'Update parent project' %}</a>
    </li>
    {% endif %}
    {% if settings.PROJECT_ISSUES and tasks_available %}
    <li>
        <a href="{% url 'project_update_tasks' project.pk %}">{% trans 'Update project tasks' %}</a>
    </li>
    {% endif %}
    {% if settings.PROJECT_VIEWS and views_available %}
    <li>
        <a href="{% url 'project_update_views' project.pk %}">{% trans 'Update project views' %}</a>
    </li>
    {% endif %}
    {% endif %}
    {% if can_delete_project %}
    <li>
        <a href="{% url 'project_delete' project.pk %}">{% trans 'Delete project' %}</a>
    </li>
    {% endif %}
</ul>
{% endif %}

{% has_perm 'projects.add_membership_object' request.user project as can_add_membership %}
{% if can_add_membership %}
<ul class="list-unstyled">
    <li>
        <a href="{% url 'membership_create' project.pk %}">{% trans 'Add member' %}</a>
    </li>
</ul>
{% endif %}

{% has_perm 'projects.add_snapshot_object' request.user project as can_add_snapshot %}
{% if can_add_snapshot %}
<ul class="list-unstyled">
    <li>
        <a href="{% url 'snapshot_create' project.pk %}">{% trans 'Create snapshot' %}</a>
    </li>
</ul>
{% endif %}

{% has_perm 'projects.add_integration_object' request.user project as can_add_integration %}
{% if providers and can_add_integration %}
<ul class="list-unstyled">
    {% for provider_key, provider in providers.items %}
    <li>
        <a href="{% url 'integration_create' project.pk provider_key %}">{{ provider.add_label }}</a>
    </li>
    {% endfor %}
</ul>
{% endif %}

<ul class="list-unstyled">
    <li>
        <a href="{% url 'projects' %}">{% trans 'Back to projects overview' %}</a>
    </li>
</ul>

{% has_perm 'projects.export_project_object' request.user project as can_export_project %}
{% if settings.PROJECT_EXPORTS and can_export_project %}
<h2 id="export-project">{% trans 'Export' %}</h2>

<ul class="list-unstyled">
    {% for key, label, class in settings.PROJECT_EXPORTS %}
    <li>
        <a href="{% url 'project_export' project.pk key %}" target="_blank">
            {{ label }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endif %}

{% has_perm 'projects.import_project_object' request.user project as can_import_project %}
{% if settings.PROJECT_IMPORTS and can_import_project %}
<h2 id="import-project">{% trans 'Import values' %}</h2>

<ul class="list-unstyled">
    <li>
        <p>
            <strong>{% trans 'Import from file' %}</strong>
        </p>
        {% url 'project_update_import' project.id as upload_url %}
        {% include 'core/upload_form.html' with upload_url=upload_url label=True %}
    </li>
    {% if settings.NESTED_PROJECTS and ancestors_import %}
    <li>
        <p>
            <strong>{% trans 'Import from parent project' %}</strong>
        </p>
        {% include 'projects/project_detail_sidebar_parent_import.html' %}
    </li>
    {% endif %}
    {% if settings.PROJECT_IMPORTS_LIST %}
    <li>
        <p>
            <strong>{% trans 'Import directly' %}</strong>
        </p>
    </li>
    {% for key, label, class in settings.PROJECT_IMPORTS %}
    {% if key in settings.PROJECT_IMPORTS_LIST %}
    <li>
        <a href="{% url 'project_update_import' project.id key %}" target="_blank">
            {{ label }}
        </a>
    </li>
    {% endif %}
    {% endfor %}
    {% endif %}
</ul>
{% endif %}

rdmo/projects/templates/projects/project_questions_add_set_button.html
{% load i18n %}

    <div class="add-set-button" ng-hide="service.project.read_only">
        <button type="button" class="btn btn-success"
                ng-click="service.addValueSet(questionset, service.joinSetPrefix(valueset.set_prefix, valueset.set_index))">
            {% blocktrans with name='{$ question.verbose_name $}' %}Add {{ name }}{% endblocktrans %}
        </button>
    </div>

rdmo/projects/templates/projects/project_questions_error.html
{% load i18n %}
{% load core_tags %}

    <p>
        {% trans 'An error occurred while retrieving the questions. Please contact support if this problem persists.' %}
    </p>

    <p class="text-danger" ng-show="service.questionset.statusText">
        {$ service.questionset.statusText $} ({$ service.questionset.status $}).
    </p>

    <p>
        <a href="{% url 'project' project.id %}">{% trans 'Back to project overview' %}</a>
    </p>

rdmo/projects/templates/projects/project_questions_form_group_file.html
{% load i18n %}

    <div class="form-group" ng-if="question.widget_type === 'file'">
        {% include 'projects/project_questions_question_label.html' %}
        {% include 'projects/project_questions_question_help.html' %}
        {% include 'projects/project_questions_question_warning.html' %}

        <div ng-if="question.is_collection">
            {% include 'projects/project_questions_add_field_help.html' %}
        </div>

        <div ng-repeat="value in service.values[question.attribute][valueset.set_prefix][valueset.set_index] track by $index">
            <div class="collection" ng-hide="value.removed">
                <div class="options">
                    {% include 'projects/project_questions_erase_field.html' %}
                    {% include 'projects/project_questions_remove_field.html' %}
                </div>

                <label class="file-control">
                    <p ng-show="value.file_url">
                        {% trans 'Currently:' %} <a href="{$ value.file_url $}" target="blank">{$ value.file_name $}</a>
                    </p>
                    <p>
                        <span ng-show="value.file_url">{% trans 'Update:' %}</span>
                        <input type="file" class="file-input"
                            ng-attr-id="id_{$ question.attribute $}_{$ valueset.set_prefix $}_{$ valueset.set_index $}_{$ $index $}"
                            ng-model="value.file"
                            ng-disabled="service.project.read_only"
                            ng-change="service.changed(value, true)" />
                    </p>
                    <ul class="text-danger list-unstyled" ng-if="value.errors.length">
                        <li ng-repeat="error in value.errors">{$ error $}</li>
                    </ul>
                </label>
            </div>
        </div>

        <div ng-if="question.is_collection">
            {% include 'projects/project_questions_add_field_button.html' %}
        </div>
    </div>

rdmo/projects/templates/projects/project_questions_form_group_text.html
{% load i18n %}

    <div class="form-group" ng-if="question.widget_type === 'text'">
        {% include 'projects/project_questions_question_label.html' %}
        {% include 'projects/project_questions_question_help.html' %}
        {% include 'projects/project_questions_question_warning.html' %}

        <div ng-if="question.is_collection">
            {% include 'projects/project_questions_add_field_help.html' %}
        </div>

        <div ng-repeat="value in service.values[question.attribute][valueset.set_prefix][valueset.set_index] track by $index">
            <div class="collection" ng-hide="value.removed">
                <div class="options">
                    {% include 'projects/project_questions_default.html' %}
                    {% include 'projects/project_questions_remove_field.html' %}
                </div>

                <input type="text" class="form-control" ng-model="value.text"
                    ng-attr-id="id_{$ question.attribute $}_{$ valueset.set_prefix $}_{$ valueset.set_index $}_{$ $index $}"
                    ng-disabled="service.project.read_only"
                    ng-change="service.changed(value)"
                    ng-class="{'default-value': service.isDefaultValue(question, value)}">
            </div>
        </div>

        <div ng-if="question.is_collection">
            {% include 'projects/project_questions_add_field_button.html' %}
        </div>
    </div>

rdmo/projects/templates/projects/project_questions_navigation_help.html
{% load i18n %}

{% if settings.PROJECT_QUESTIONS_AUTOSAVE %}
<p class="help-block">
    {% trans 'Using the navigation will save your input.' %}
</p>
{% else %}
<p class="help-block">
    {% trans 'Please note that using the navigation will discard any unsaved input.' %}
</p>
{% endif %}

<p class="help-block">
{% blocktrans trimmed %}
Entries with <i class="fa fa-question-circle-o small" aria-hidden="true"></i> might be skipped based on your input.
{% endblocktrans %}
</p>